const automotive_industry = [
    {"label": "Automekaanikko"},
    {"label": "Automaalari"},
    {"label": "Automyyjä"},
    {"label": "Katsastaja"},
    {"label": "Varaosamyyjä"},

]
const food_industry = [
    {"label": "Elintarvikekemisti"},
    {"label": "Elintarviketyöntekijä"},
    {"label": "Hankintapäällikkö, meijeriteollisuus"},
    {"label": "Kondiittori"},
    {"label": "Leipomotyöntekijä"},
    {"label": "Leipuri"},
    {"label": "Lihanleikkaaja"},
    {"label": "Lihavalmistetyöntekijä"},
    {"label": "Mylläri"},
    {"label": "Elintarvikepakkaaja"},
    {"label": "Juomatyöntekijä"},
    {"label": "Säilyketyöntekijä"},
    {"label": "Teurastaja"},
    {"label": "Elintarviketuotannon työnjohtaja"},
    {"label": "Tuotannonsuunnittelija, elintarviketeollisuus"},
    {"label": "Tuotantopäällikkö, meijeriteollisuus"},
    {"label": "Meijeristi, meijerituotteiden valmistaja"},

]
const energy_sector = [
    {"label": "Automaatioasentaja"},
    {"label": "Automaatioinsinööri"},
    {"label": "Biotekniikan insinööri"},
    {"label": "Elektroniikka-asentaja"},
    {"label": "Elektroniikkainsinööri"},
    {"label": "Energianeuvoja"},
    {"label": "Energiatekniikan insinööri"},
    {"label": "Hakkurinkuljettaja"},
    {"label": "Huoltopäällikkö, kylmäala"},
    {"label": "Kaukolämpöasentaja"},
    {"label": "Kaukolämpöinsinööri"},
    {"label": "Insinööri, kemiantekniikka"},
    {"label": "Kemisti"},
    {"label": "Kunnossapitoinsinööri"},
    {"label": "Kylmäsuunnittelija"},
    {"label": "Käyttöinsinööri"},
    {"label": "LVI-asentaja"},
    {"label": "LVI-insinööri"},
    {"label": "Laborantti"},
    {"label": "Lämpöyrittäjä"},
    {"label": "Metsuri"},
    {"label": "Metsäkoneenkuljettaja"},
    {"label": "Metsätalouden harjoittaja"},
    {"label": "Metsätalousinsinööri"},
    {"label": "Sähköasentaja"},
    {"label": "Sähköinsinööri"},
    {"label": "Sähkömestari, meriliikenne"},
    {"label": "Sähköverkostoasentaja"},
    {"label": "Tuulivoimainsinööri"},
    {"label": "Voimalaitoksen käyttäjä"},
    {"label": "Voimalaitospäällikkö"},
    {"label": "Huoltoteknikko"},
]

const Pharmaceutical_industry = [
    {"label": "Apteekkari"},
    {"label": "Väitöskirjatutkija"},
    {"label": "Biokemisti"},
    {"label": "Farmaseutti"},
    {"label": "Kemisti"},
    {"label": "Lääketeknikko"},
    {"label": "Mikrobiologi"},
    {"label": "Myyntiedustaja"},
    {"label": "Proviisori"},

]
const administration = [
    {"label": "Arkistonhoitaja"},
    {"label": "Controller"},
    {"label": "Energianeuvoja"},
    {"label": "Juristi"},
    {"label": "Henkilöstökonsultti"},
    {"label": "Henkilöstöpäällikkö"},
    {"label": "Järjestöjohtaja"},
    {"label": "Järjestösihteeri"},
    {"label": "Kiinteistösihteeri"},
    {"label": "Kirjanpitäjä"},
    {"label": "Pankinjohtaja"},
    {"label": "Kulttuurisihteeri"},
    {"label": "Kuvaussihteeri"},
    {"label": "Lähetti"},
    {"label": "Matkailujohtaja"},
    {"label": "Palkanlaskija"},
    {"label": "Teknologiajohtaja"},
    {"label": "Assistentti"},
    {"label": "Sosiaalialan laitoksen johtaja"},
    {"label": "Sosiaalijohtaja"},
    {"label": "Suunnittelijat, tietotekniikka"},
    {"label": "Tilastopäällikkö"},
    {"label": "Tilintarkastaja"},
    {"label": "Toimistosihteeri"},
    {"label": "Tukkukaupan johtaja"},
    {"label": "Tulkki"},
    {"label": "Ympäristötarkastaja"},
    {"label": "Ympäristöjohtaja"},
    {"label": "Yritysneuvoja"},
    {"label": "Erityisasiantuntija, julkinen hallinto"},
    {"label": "Kunnanjohtaja"},
    {"label": "Data-analyytikko"},
    {"label": "Tietoturva-asiantuntija"},

]
const Hair_and_beauty_care = [
    {"label": "Kosmetiikkamyyjä"},
    {"label": "Kosmetologi"},
    {"label": "Maskeeraaja"},
    {"label": "Parturi-kampaaja"},
    {"label": "Stylisti"},
    {"label": "Tatuoija, lävistäjä"},

]
const Hotel_and_restaurant = [
    {"label": "Baarimestari"},
    {"label": "Myyntineuvottelija, matkailu"},
    {"label": "Ravintolan vuoropäällikkö"},
    {"label": "Keittiöpäällikkö"},
    {"label": "Kokki"},
    {"label": "Kondiittori"},
    {"label": "Leipomotyöntekijä"},
    {"label": "Leipuri"},
    {"label": "Myyntipäällikkö"},
    {"label": "Tarjoilija"},
    {"label": "Ravintolapäällikkö"},
    {"label": "Ravintolatyöntekijä"},
    {"label": "Ravitsemispäällikkö"},
    {"label": "Ruokapalvelutyöntekijä"},
    {"label": "Siivoustyönjohtaja"},
    {"label": "Suurtalouskokki"},
    {"label": "Hotellipäällikkö"},
    {"label": "Vastaanottovirkailija"},
    {"label": "Kerrossiivooja"},
    {"label": "Kylmäkkö"},
    {"label": "Barista"},

]
const ict_industry = [
    {"label": "ICT-tukihenkilö"},
    {"label": "Ohjelmistokehittäjä"},
    {"label": "Palvelinohjelmoija"},
    {"label": "Peliartisti"},
    {"label": "Pelin äänisuunnittelija"},
    {"label": "Peliohjelmoija"},
    {"label": "Pelisuunnittelija"},
    {"label": "Pelitestaaja"},
    {"label": "Pelituottaja"},
    {"label": "Teknologiajohtaja"},
    {"label": "Suunnittelijat, tietotekniikka"},
    {"label": "Tietokoneasentaja"},
    {"label": "Tietoliikenneasentaja"},
    {"label": "Tietoliikenneinsinööri"},
    {"label": "Webmaster"},
    {"label": "Yhteisömanageri"},
    {"label": "Tietoturva-asiantuntija"},

]
const mining = [
    {"label": "Geologi"},
    {"label": "Kaivosinsinööri"},
    {"label": "Kaivostyöntekijä"},

]
const education = [
    {"label": "Ammatillisen oppilaitoksen opettaja"},
    {"label": "Väitöskirjatutkija"},
    {"label": "Erityisopettaja"},
    {"label": "Kääntäjä"},
    {"label": "Kieltenopettaja"},
    {"label": "Kotitalousopettaja"},
    {"label": "Koulukuraattori"},
    {"label": "Koulunkäynninohjaaja"},
    {"label": "Koulutussuunnittelija"},
    {"label": "Lasten ja nuorten erityisohjaaja"},
    {"label": "Lastenohjaaja"},
    {"label": "Varhaiskasvatuksen opettaja"},
    {"label": "Lehtori, yliopistot ja korkeakoulut"},
    {"label": "Liikenneopettaja"},
    {"label": "Liikunnanopettaja"},
    {"label": "Luokanopettaja"},
    {"label": "Lähihoitaja, lasten ja nuorten kasvatus ja hoito"},
    {"label": "Opettaja, ammattikorkeakoulu"},
    {"label": "Opettaja, matemaattis-luonnontieteelliset aineet"},
    {"label": "Opettaja, musiikki"},
    {"label": "Opettaja, reaaliaineet"},
    {"label": "Opettaja, taide- ja taitoaineet"},
    {"label": "Opinto-ohjaaja"},
    {"label": "Opintosihteeri"},
    {"label": "Perhepäivähoidon ohjaaja"},
    {"label": "Perhepäivähoitaja"},
    {"label": "Professori"},
    {"label": "Päiväkotiapulainen"},
    {"label": "Ratsastuksenopettaja"},
    {"label": "Rehtori"},
    {"label": "Tutkimuspäällikkö"},
    {"label": "Yhteiskuntatutkija"},
    {"label": "Äidinkielen opettaja"},

]
const property_services = [
    {"label": "Automaatioasentaja"},
    {"label": "Automaatioinsinööri"},
    {"label": "Hyttisiivooja"},
    {"label": "Ikkunanpesijä"},
    {"label": "Isännöitsijä"},
    {"label": "Järjestyksenvalvoja"},
    {"label": "Kiinteistönhoitaja"},
    {"label": "Kiinteistösihteeri"},
    {"label": "Kiinteistötyönjohtaja"},
    {"label": "Kylmäasentaja"},
    {"label": "Kylmäsuunnittelija"},
    {"label": "LVI-asentaja"},
    {"label": "LVI-insinööri"},
    {"label": "Liikuntapaikkojenhoitaja"},
    {"label": "Pysäköinnintarkastaja"},
    {"label": "Siivooja"},
    {"label": "Siivoustyönjohtaja"},
    {"label": "Talonmies"},
    {"label": "Toimistosihteeri"},
    {"label": "Vartija"},
    {"label": "Kerrossiivooja"},

]
const culture_and_entertainment = [
    {"label": "Arkeologi"},
    {"label": "Dramaturgi"},
    {"label": "Elokuvaaja"},
    {"label": "Elokuvaleikkaaja"},
    {"label": "Elokuvaohjaaja"},
    {"label": "Video- ja elokuvatuottaja"},
    {"label": "Informaatikko"},
    {"label": "Järjestyksenvalvoja"},
    {"label": "Kirjailija"},
    {"label": "Kirjastonhoitaja"},
    {"label": "Kirjastovirkailija"},
    {"label": "Konservaattori"},
    {"label": "Kriitikko"},
    {"label": "Kuiskaaja"},
    {"label": "Kulttuuriohjaaja"},
    {"label": "Kulttuurisihteeri"},
    {"label": "Kulttuurituottaja"},
    {"label": "Kuvanauhoittaja"},
    {"label": "Kuvatarkkailija"},
    {"label": "Laulaja, kevyt musiikki"},
    {"label": "Laulaja, taidemusiikki"},
    {"label": "Lavastaja"},
    {"label": "Maskeeraaja"},
    {"label": "Museoamanuenssi"},
    {"label": "Musiikkiterapeutti"},
    {"label": "Muusikko (kevyt musiikki)"},
    {"label": "Näyttelijä"},
    {"label": "Näyttämömestari"},
    {"label": "Ohjaaja"},
    {"label": "Orkesterimuusikko"},
    {"label": "Orkesterin- ja kuoronjohtaja"},
    {"label": "Pianonvirittäjä"},
    {"label": "Puvustaja"},
    {"label": "Puvustonhoitaja"},
    {"label": "Roudari"},
    {"label": "Säveltäjä"},
    {"label": "TV-, elokuva- ja videokääntäjä"},
    {"label": "Tanssitaiteilija"},
    {"label": "Televisiokuvaaja"},
    {"label": "Valaistusmestari"},
    {"label": "Valaistustarkkailija"},
    {"label": "Valokuvaaja"},
    {"label": "Äänitarkkailija"},
    {"label": "Äänittäjä"},

]
const manual_skills = [
    {"label": "Aseseppä"},
    {"label": "Huonekalujen entisöijä"},
    {"label": "Verhoilija"},
    {"label": "Kelloseppä"},
    {"label": "Kengitysseppä"},
    {"label": "Keramiikka- ja lasitaiteilija"},
    {"label": "Kirjansitoja"},
    {"label": "Konservaattori"},
    {"label": "Koristemaalari"},
    {"label": "Koristepuuseppä"},
    {"label": "Kultaseppä"},
    {"label": "Kutoja"},
    {"label": "Kuvanveistäjä"},
    {"label": "Lasinpuhaltaja"},
    {"label": "Modisti"},
    {"label": "Ompelija-artesaani"},
    {"label": "Piirtäjä"},
    {"label": "Pukusuunnittelija"},
    {"label": "Puuseppä"},
    {"label": "Satulaseppä"},
    {"label": "Seppä"},
    {"label": "Sisustusarkkitehti"},
    {"label": "Soitinrakentaja"},
    {"label": "Suutari"},
    {"label": "Taidegraafikko"},
    {"label": "Taidemaalari"},
    {"label": "Tekstiilisuunnittelija"},
    {"label": "Teollinen muotoilija"},
    {"label": "Turkistuotteiden valmistaja"},
    {"label": "Turkkuri"},
    {"label": "Vaatesuunnittelija"},
    {"label": "Vaatturi"},
    {"label": "Venepuuseppä"},
    {"label": "Visualisti"},
    {"label": "Sisustussuunnittelija"},

]
const legal_field = [
    {"label": "Asianajaja"},
    {"label": "Juristi"},
    {"label": "Syyttäjä"},
    {"label": "Tuomari"},
    {"label": "Erityisasiantuntija, julkinen hallinto"},

]
const air_service = [
    {"label": "Helikopterilentäjä"},
    {"label": "Lentokonekuormaaja"},
    {"label": "Lennonjohtaja"},
    {"label": "Lennonjohdon avustaja"},
    {"label": "Lentoemäntä, stuertti"},
    {"label": "Lentokoneasentaja"},
    {"label": "Lentokonelevyseppä"},
    {"label": "Liikennelentäjä"},
    {"label": "Lentokenttävirkailija"},
    {"label": "Rahtivirkailija"},
    {"label": "Turvatarkastaja"},

]
const traffic_and_logistics = [
    {"label": "Helikopterilentäjä"},
    {"label": "Lentokonekuormaaja"},
    {"label": "Lennonjohtaja"},
    {"label": "Lennonjohdon avustaja"},
    {"label": "Lentoemäntä, stuertti"},
    {"label": "Lentokoneasentaja"},
    {"label": "Lentokonelevyseppä"},
    {"label": "Liikennelentäjä"},
    {"label": "Lentokenttävirkailija"},
    {"label": "Rahtivirkailija"},
    {"label": "Turvatarkastaja"},

]
const logistics_services = [
    {"label": "Ahtaaja"},
    {"label": "Ajojärjestelijä"},
    {"label": "Huolitsija"},
    {"label": "Kuljetussuunnittelija"},
    {"label": "Logistiikkainsinööri"},
    {"label": "Lähetti"},
    {"label": "Pakkaaja"},
    {"label": "Polkupyörälähetti"},
    {"label": "Postinjakaja"},
    {"label": "Postinlajittelija"},
    {"label": "Terminaalityöntekijä"},
    {"label": "Varastonhoitaja"},
    {"label": "Varastotyöntekijä"},

]
const maritime_transport = [
    {"label": "Ahtaaja"},
    {"label": "Merikapteeni"},
    {"label": "Alusliikenneohjaaja"},
    {"label": "Hyttisiivooja"},
    {"label": "Kokki"},
    {"label": "Konemestari"},
    {"label": "Konemies-korjaaja"},
    {"label": "Konepäällikkö"},
    {"label": "Laivan purseri"},
    {"label": "Laivuri-kuljettaja"},
    {"label": "Luotsi"},
    {"label": "Matruusi-pursimies"},
    {"label": "Pelinhoitaja"},
    {"label": "Perämies"},
    {"label": "Tarjoilija"},
    {"label": "Sähkömestari, meriliikenne"},
    {"label": "Yliperämies"},

]
const railway_traffic = [
    {"label": "Asentaja, rautatieliikenne"},
    {"label": "Konduktööri"},
    {"label": "Liikenneohjaaja, rautatieliikenne"},
    {"label": "Ratapihatyöntekijä"},
    {"label": "Tarjoilija"},
    {"label": "Veturinkuljettaja"},

]
const road_traffic = [
    {"label": "Ajojärjestelijä"},
    {"label": "Hinausautonkuljettaja"},
    {"label": "Kuljetussuunnittelija"},
    {"label": "Kuorma-autonkuljettaja"},
    {"label": "Linja-autonkuljettaja"},
    {"label": "Taksinkuljettaja"},
    {"label": "Terminaalityöntekijä"},
    {"label": "Yhdistelmäajoneuvonkuljettaja"},

]
const exercise_and_sports = [
    {"label": "Ammattiurheilija"},
    {"label": "Liikunnanohjaaja"},
    {"label": "Liikunnanopettaja"},
    {"label": "Liikuntapaikkojenhoitaja"},
    {"label": "Ratsastuksenopettaja"},
    {"label": "Uimavalvoja"},
    {"label": "Urheilukaupan myyjä"},
    {"label": "Urheiluvalmentaja"},
    {"label": "Hiihdonopettaja"},

]
const national_defense_and_border = [
    {"label": "Aliupseeri"},
    {"label": "Erikoisupseeri"},
    {"label": "Merivartija"},
    {"label": "Rajavartija"},
    {"label": "Siviilityöntekijä, maanpuolustus"},
    {"label": "Tullitarkastaja"},
    {"label": "Upseeri"},
    {"label": "Sopimussotilas"},
    {"label": "Rauhanturvaaja"},

]
const agricultural = [
    {"label": "Agrologi"},
    {"label": "Agronomi"},
    {"label": "Eläinlääkäri"},
    {"label": "Eläintenhoitaja"},
    {"label": "Hevostenhoitaja"},
    {"label": "Kengitysseppä"},
    {"label": "Luomutuottaja, luomuviljelijä"},
    {"label": "Maanviljelijä"},
    {"label": "Maatalouslomittaja"},
    {"label": "Maatalousneuvoja"},
    {"label": "Maataloustyönjohtaja"},
    {"label": "Maataloustyöntekijä"},
    {"label": "Poronhoitaja"},
    {"label": "Siipikarjanhoitaja"},
    {"label": "Sikalanhoitaja"},
    {"label": "Tuotantoeläintenhoitaja"},
    {"label": "Turkiseläintenhoitaja"},
    {"label": "Turkistarhaaja"},

]
const travel_and_leisure = [
    {"label": "Eräopas"},
    {"label": "Rinnetyöntekijä"},
    {"label": "Myyntineuvottelija, matkailu"},
    {"label": "Laitetyöntekijä"},
    {"label": "Laivan purseri"},
    {"label": "Luonto-ohjaaja"},
    {"label": "Matkailujohtaja"},
    {"label": "Matka-asiantuntija"},
    {"label": "Matkailuyrittäjä"},
    {"label": "Matkaopas"},
    {"label": "Myyntipäällikkö"},
    {"label": "Pelinhoitaja"},
    {"label": "Hotellipäällikkö"},
    {"label": "Vastaanottovirkailija"},
    {"label": "Hiihdonopettaja"},
    {"label": "Ohjelmapalvelutyöntekijä"},

]
const wood_industry = [
    {"label": "Insinööri, paperiteollisuus"},
    {"label": "Insinööri, kemiantekniikka"},
    {"label": "Lastulevytyöntekijä"},
    {"label": "Paperikoneenhoitaja"},
    {"label": "Prosessinhoitaja (paperiteollisuus)"},
    {"label": "Prosessitekniikan insinööri"},
    {"label": "Puuinsinööri"},
    {"label": "Puutavaranlajittelija"},
    {"label": "Sahatyöntekijä"},
    {"label": "Sellunvalmistaja"},
    {"label": "Vanerityöntekijä"},

]
const forest_sector = [
    {"label": "Eräopas"},
    {"label": "Hakkurinkuljettaja"},
    {"label": "Kartoittaja"},
    {"label": "Keruutuoteneuvoja"},
    {"label": "Keruutuotetarkastaja"},
    {"label": "Luonnonvaratuottaja"},
    {"label": "Metsuri"},
    {"label": "Metsäkoneenkuljettaja"},
    {"label": "Metsänhoitaja"},
    {"label": "Metsätalouden harjoittaja"},
    {"label": "Metsätalousinsinööri"},
    {"label": "Poimija"},
    {"label": "Yhdistelmäajoneuvonkuljettaja"},

]
const sales_and_marketing = [
    {"label": "Art Director"},
    {"label": "Asiakaspäällikkö"},
    {"label": "Sosiaalisen median vaikuttaja"},
    {"label": "Copywriter"},
    {"label": "Eläinkaupan myyjä"},
    {"label": "Huonekalumyyjä"},
    {"label": "Kello- ja kultasepänliikkeen myyjä"},
    {"label": "Kiinteistönvälittäjä"},
    {"label": "Kioskimyyjä"},
    {"label": "Kirjakaupanmyyjä"},
    {"label": "Kodinkonemyyjä"},
    {"label": "Kosmetiikkamyyjä"},
    {"label": "Kuluttajaneuvoja"},
    {"label": "Mainospäällikkö"},
    {"label": "Malli"},
    {"label": "Markkinointipäällikkö"},
    {"label": "Mediasuunnittelija"},
    {"label": "Myymälänhoitaja"},
    {"label": "Myyntiedustaja"},
    {"label": "Myyntipäällikkö"},
    {"label": "Ostaja"},
    {"label": "Palvelumuotoilija"},
    {"label": "Tekstiilimyyjä"},
    {"label": "Torimyyjä"},
    {"label": "Tubettaja"},
    {"label": "Tukkukaupan johtaja"},
    {"label": "Tuotantotalouden insinööri"},
    {"label": "Tuote-esittelijä"},
    {"label": "Urheilukaupan myyjä"},
    {"label": "Valokuvaustarvikemyyjä"},
    {"label": "Visualisti"},
    {"label": "Vähittäiskauppias"},
    {"label": "Markkinointiassistentti"},
    {"label": "Yleismyyjä"},
    {"label": "Verkkokauppatyöntekijä"},

]
const fire_and_rescue = [
    {"label": "Helikopterilentäjä"},
    {"label": "Hätäkeskuspäivystäjä"},
    {"label": "Nuohooja"},
    {"label": "Paloesihenkilö"},
    {"label": "Palomies"},
    {"label": "Palopäällikkö"},

]
const police_and_criminal_sanction = [
    {"label": "Erikoissuunnittelija (rikosseuraamusala)"},
    {"label": "Komisario"},
    {"label": "Konstaapeli"},
    {"label": "Poliisipäällikkö"},
    {"label": "Rikosseuraamusesihenkilo, vankila"},
    {"label": "Rikosseuraamusesihenkilo, yhdyskuntaseuraamustoimisto"},
    {"label": "Rikosseuraamustyöntekijä"},
    {"label": "Vartija, rikosseuraamusala"},
    {"label": "Ylikonstaapeli"},
    {"label": "Poliisi"},

]
const garden_and_green = [
    {"label": "Floristi"},
    {"label": "Hortonomi"},
    {"label": "Maanviljelijä"},
    {"label": "Maisema-arkkitehti"},
    {"label": "Puutarhatyöntekijä"},
    {"label": "Puutarhuri"},
    {"label": "Viherrakentaja"},

]
const finance_and_insurance = [
    {"label": "Analyytikko"},
    {"label": "Asiakaspäällikkö"},
    {"label": "Pankinjohtaja"},
    {"label": "Matemaatikko"},
    {"label": "Meklari"},
    {"label": "Palveluneuvoja"},
    {"label": "Pankkitoimihenkilö"},
    {"label": "Rahoitusasiantuntija"},
    {"label": "Tilastopäällikkö"},
    {"label": "Tilastotutkija"},
    {"label": "Vakuutusmyyjä"},
    {"label": "Vakuutusvirkailija"},
    {"label": "Valuutta- ja rahamarkkinadealer"},

]
const construction = [
    {"label": "Ajoneuvonosturinkuljettaja"},
    {"label": "Arkkitehti"},
    {"label": "Asfalttityöntekijä"},
    {"label": "Elementtiasentaja"},
    {"label": "Elementtityöntekijä"},
    {"label": "Hitsaaja"},
    {"label": "Ikkuna- ja oviasentaja"},
    {"label": "Kaivinkoneenkuljettaja"},
    {"label": "Kattoasentaja"},
    {"label": "Kirvesmies"},
    {"label": "Kuntotarkastaja"},
    {"label": "LVI-asentaja"},
    {"label": "LVI-insinööri"},
    {"label": "Lasittaja"},
    {"label": "Lattianpäällystäjä"},
    {"label": "Maanmittausinsinööri"},
    {"label": "Maanrakennusinsinööri"},
    {"label": "Maanrakennuskoneen asentaja"},
    {"label": "Muurari"},
    {"label": "Pintakäsittelijä"},
    {"label": "Puuseppä"},
    {"label": "Rakennesuunnittelija"},
    {"label": "Rakennusinsinööri"},
    {"label": "Rakennuskonetyöntekijä"},
    {"label": "Rakennusmaalari"},
    {"label": "Rakennusmestari"},
    {"label": "Rakennustyöntekijä"},
    {"label": "Raudoittaja"},
    {"label": "Suunnitteluassistentti"},
    {"label": "Sähköasentaja"},
    {"label": "Tekninen eristäjä"},
    {"label": "Maanrakennuskoneenkuljettaja"},
    {"label": "Torninosturinkuljettaja"},
    {"label": "Tuotantotalouden insinööri"},
    {"label": "Työnjohtaja (maanrakennusala)"},
    {"label": "Yhdyskuntarakentaja"},

]
const nursing = [
    {"label": "Apuvälineteknikko"},
    {"label": "Bioanalyytikko"},
    {"label": "Ensihoitaja"},
    {"label": "Fysiologi"},
    {"label": "Geneetikko"},
    {"label": "Hoiva-avustaja"},
    {"label": "Kuulontutkija"},
    {"label": "Kätilö"},
    {"label": "Laborantti"},
    {"label": "Lähihoitaja, kuntoutus"},
    {"label": "Lähihoitaja, lasten ja nuorten kasvatus ja hoito"},
    {"label": "Lähihoitaja, mielenterveys- ja päihdetyö"},
    {"label": "Lähihoitaja, sairaanhoito ja huolenpito"},
    {"label": "Lähihoitaja, vammaistyö"},
    {"label": "Lähihoitaja, ikääntyvien hoito ja kuntoutus"},
    {"label": "Lääkintävahtimestari-sairaankuljettaja"},
    {"label": "Lääkäri"},
    {"label": "Optikko"},
    {"label": "Psykologi"},
    {"label": "Psykoterapeutti"},
    {"label": "Röntgenhoitaja"},
    {"label": "Sairaala-apulainen"},
    {"label": "Sairaanhoitaja"},
    {"label": "Terveydenhoitaja"},
    {"label": "Välinehuoltaja"},
    {"label": "Ylihoitaja"},
    {"label": "Obduktioteknikko"},

]
const social_sector = [
    {"label": "Henkilökohtainen avustaja"},
    {"label": "Hoiva-avustaja"},
    {"label": "Kehitysvammaisten ohjaaja"},
    {"label": "Kehitysvammaistenhoitaja"},
    {"label": "Kodinhoitaja"},
    {"label": "Koulukuraattori"},
    {"label": "Koulunkäynninohjaaja"},
    {"label": "Kulttuuriohjaaja"},
    {"label": "Kuntoutusohjaaja"},
    {"label": "Lasten ja nuorten erityisohjaaja"},
    {"label": "Lastenohjaaja"},
    {"label": "Nuoriso-ohjaaja"},
    {"label": "Nuorisosihteeri"},
    {"label": "Pakolaistyöntekijä"},
    {"label": "Psykologi"},
    {"label": "Sosiaalialan laitoksen johtaja"},
    {"label": "Sosiaalijohtaja"},
    {"label": "Sosiaaliohjaaja"},
    {"label": "Sosiaaliterapeutti"},
    {"label": "Sosiaalityöntekijä"},
    {"label": "Tulkki"},
    {"label": "Tutkimuspäällikkö"},
    {"label": "Viittomakielen ohjaaja"},
    {"label": "Viittomakielen tulkki"},
    {"label": "Yhteisöpedagogi"},

]
const oral_health_care = [
    {"label": "Hammaslaborantti"},
    {"label": "Hammaslääkäri"},
    {"label": "Hammasteknikko"},
    {"label": "Lähihoitaja, suunhoito"},
    {"label": "Suuhygienisti"},
    {"label": "Välinehuoltaja"},

]
const technology_industry = [
    {"label": "Automaatioasentaja"},
    {"label": "Automaatioinsinööri"},
    {"label": "Elektroniikka-asentaja"},
    {"label": "Elektroniikkainsinööri"},
    {"label": "Energiatekniikan insinööri"},
    {"label": "Fyysikko"},
    {"label": "Hienomekaanikko"},
    {"label": "Hitsaaja"},
    {"label": "Insinööri, metallien jalostus"},
    {"label": "Kokoonpanija, elektroniikka- ja sähköteollisuus"},
    {"label": "Kokoonpanija, kone- ja metallituoteteollisuus"},
    {"label": "Koneenasentaja"},
    {"label": "Koneinsinööri"},
    {"label": "Koneistaja"},
    {"label": "Konejyrsijä"},
    {"label": "Konetyöntekijä"},
    {"label": "Lentokoneasentaja"},
    {"label": "Lentokonelevyseppä"},
    {"label": "Levyseppähitsaaja"},
    {"label": "Mekatroniikka-asentaja"},
    {"label": "Mikromekaanikko"},
    {"label": "Prosessitekniikan insinööri"},
    {"label": "Rautarakennetyöntekijä"},
    {"label": "Sinkittäjä"},
    {"label": "Sorvaaja"},
    {"label": "Suunnitteluassistentti"},
    {"label": "Sähköinsinööri"},
    {"label": "Sähkökoneenasentaja"},
    {"label": "Tarkastusinsinööri, kone- ja metallituoteteollisuus"},
    {"label": "Tekninen eristäjä"},
    {"label": "Teollisuusputkiasentaja"},
    {"label": "Teräsrakentaja, rautarakennetyöntekijä"},
    {"label": "Tietokoneasentaja"},
    {"label": "Tietoliikenneasentaja"},
    {"label": "Tietoliikenneinsinööri"},
    {"label": "Tuotantotalouden insinööri"},
    {"label": "Työvälinevalmistaja"},
    {"label": "Valaja"},
    {"label": "Valumallin valmistaja"},
    {"label": "Ympäristöinsinööri"},

]
const textile_and_clothing = [
    {"label": "Verhoilija"},
    {"label": "Kutoja"},
    {"label": "Leikkaaja, tekstiili- ja vaatetusteollisuus"},
    {"label": "Mallimestari"},
    {"label": "Ompelija"},
    {"label": "Pukusuunnittelija"},
    {"label": "Suutari"},
    {"label": "Insinööri, tekstiili- ja vaatetusteollisuus"},
    {"label": "Tekstiilihuoltaja"},
    {"label": "Tekstiilimyyjä"},
    {"label": "Tekstiilisuunnittelija"},
    {"label": "Vaatesuunnittelija"},
    {"label": "Vaatturi"},
    {"label": "Viimeistelyn tekstiilityöntekijä"},
    {"label": "Visualisti"}
]


const services_promote_health = [
    {"label": "Fysioterapeutti"},
    {"label": "Hieroja"},
    {"label": "Jalkaterapeutti"},
    {"label": "Kosmetologi"},
    {"label": "Kuntoutusohjaaja"},
    {"label": "Naprapaatti"},
    {"label": "Osteopaatti"},
    {"label": "Puheterapeutti"},
    {"label": "Ravitsemusterapeutti"},
    {"label": "Taideterapeutti"},
    {"label": "Toimintaterapeutti"},
    {"label": "Geronomi"},

]
const religious_work = [
    {"label": "Diakoniatyöntekijä"},
    {"label": "Evankelisluterilainen pappi"},
    {"label": "Hautaustoimistotyöntekijä"},
    {"label": "Kirkkomuusikko"},
    {"label": "Lastenohjaaja"},
    {"label": "Ortodoksinen pappi"},
    {"label": "Suntio"},

]
const broadcast = [
    {"label": "Sosiaalisen median vaikuttaja"},
    {"label": "Copywriter"},
    {"label": "Graafinen suunnittelija"},
    {"label": "Kääntäjä"},
    {"label": "Kirjailija"},
    {"label": "Kriitikko"},
    {"label": "Kustannustoimittaja"},
    {"label": "Kuvanauhoittaja"},
    {"label": "Kuvatarkkailija"},
    {"label": "Kuvaussihteeri"},
    {"label": "Mediasuunnittelija"},
    {"label": "Piirtäjä"},
    {"label": "Radio- ja televisiotoimittaja"},
    {"label": "TV-, elokuva- ja videokääntäjä"},
    {"label": "TV-tuottaja"},
    {"label": "Viestinnän asiantuntija"},
    {"label": "Toimittaja"},
    {"label": "Toimituspäällikkö"},
    {"label": "Tubettaja"},
    {"label": "Valokuvaaja"},
    {"label": "Erityisasiantuntija, julkinen hallinto"},

]
const private_security = [
    {"label": "Elektroniikka-asentaja"},
    {"label": "Järjestyksenvalvoja"},
    {"label": "Pysäköinnintarkastaja"},
    {"label": "Turvatyöntekijä"},
    {"label": "Vartija"},
    {"label": "Yksityisetsivä"},

]
const environmental_sector = [
    {"label": "Biokemisti"},
    {"label": "Biotekniikan insinööri"},
    {"label": "Ekologi"},
    {"label": "Geologi"},
    {"label": "Iktyonomi"},
    {"label": "Jäteasemanhoitaja"},
    {"label": "Jäteautonkuljettaja"},
    {"label": "Jäteneuvoja"},
    {"label": "Kaatopaikanhoitaja"},
    {"label": "Kalastusbiologi"},
    {"label": "Kalatalousneuvoja"},
    {"label": "Kartoittaja"},
    {"label": "Kasvitieteilijä"},
    {"label": "Kemisti"},
    {"label": "Laborantti"},
    {"label": "Limnologi ja hydrobiologi"},
    {"label": "Luonto- ja ympäristöneuvoja"},
    {"label": "Meteorologi"},
    {"label": "Mikrobiologi"},
    {"label": "Puhdistamonhoitaja"},
    {"label": "Terveystarkastaja"},
    {"label": "Ympäristöinsinööri"},
    {"label": "Ympäristökasvattaja"},
    {"label": "Ympäristösuunnittelija"},
    {"label": "Ympäristötarkastaja"},
    {"label": "Ympäristöjohtaja"},
    {"label": "Ympäristötyöntekijä"},
]




  const options = [
      {"label": 'AUTOALA', items: automotive_industry, icon: 'fas fa-car-side'},
      {"label": 'Elintarviketeollisuus', items: food_industry},
      {"label": 'Energia-ala', items: energy_sector},
      {"label": 'Farmasia-ala', items: Pharmaceutical_industry},
      {"label": 'Hallinto', items: administration},
      {"label": 'Hius- ja kauneudenhoito', items: Hair_and_beauty_care},
      {"label": 'Hotelli ja ravintola', items: Hotel_and_restaurant},


      {"label": "ICT-ala", "items": ict_industry},
      {"label": "Kaivostoiminta​", "items": mining},
      {"label": "Kasvatus, opetus ja koulutus", "items": education},
      {"label": "Kiinteistöpalvelut", "items": property_services},
      {"label": "Kulttuuri ja viihde", "items": culture_and_entertainment},
      {"label": "Kädentaidot", "items": manual_skills},
      {"label": "Lakiala", "items": legal_field},
      {"label": "Lentoliikenne", "items": air_service},
      {"label": "Liikenne ja logistiikka", "items": traffic_and_logistics},
      {"label": "Logistiikkapalvelut", "items": logistics_services},
      {"label": "Meriliikenne", "items": maritime_transport},
      {"label": "Rautatieliikenne", "items": railway_traffic},
      {"label": "Tieliikenne", "items": road_traffic},
      {"label": "Liikunta ja urheilu", "items": exercise_and_sports},
      {"label": "Maanpuolustus ja rajavalvonta", "items": national_defense_and_border},
      {"label": "Maatalous", "items": agricultural},
      {"label": "Matkailu ja vapaa-aika", "items": travel_and_leisure},
      {"label": "Metsä- ja puuteollisuus", "items": wood_industry},
      {"label": "Metsä-ala", "items": forest_sector},
      {"label": "Myynti ja markkinointi", "items": sales_and_marketing},
      {"label": "Palo- ja pelastusala", "items": fire_and_rescue},
      {"label": "Poliisi ja rikosseuraamus", "items": police_and_criminal_sanction},
      {"label": "Puutarha- ja viherala", "items": garden_and_green},
      {"label": "Rahoitus- ja vakuutusala", "items": finance_and_insurance},
      {"label": "Rakentaminen", "items": construction},
      {"label": "Sairaanhoito", "items": nursing},
      {"label": "Sosiaaliala", "items": social_sector},
      {"label": "Suun terveydenhuolto", "items": oral_health_care},
      {"label": "Teknologiateollisuus", "items": technology_industry},
      {"label": "Tekstiili- ja vaatetusteollisuus", "items": textile_and_clothing},
      {"label": "Terveyttä edistävät palvelut", "items": services_promote_health},
      {"label": "Uskonnollinen työ", "items": religious_work},
      {"label": "Viestintä", "items": broadcast},
      {"label": "Yksityinen turvallisuusala", "items": private_security},
      {"label": "Ympäristöala", "items": environmental_sector}
    ]



export default options;